### ISSUE TITLE
Markers flicker when scrolling on the map

### ISSUE THREAD

**Issue by CrissAlvarezH** [google-map-react/google-map-react#1117]
When the map is scrolled and the mouse is released, the markers blink from where they were initially positioned.

**The code**

```
import React from "react";
import GoogleMapReact from 'google-map-react';


const AnyReactComponent = ({ text }) => (
    <div style={{
        width: "70px",
        backgroundColor: "black",
        color: "white",
        padding: 2,
        textAlign: "center"
    }}>
        {text}
    </div>
);

const center =     {
    lat: 8.789109769101659,
    lng: -75.85785616189241,
}

const zoom = 17

export default function SimpleMap(){
  console.log("simple map render")
  return (
    <div style={{ height: '100vh', width: '100%' }}>
      <GoogleMapReact
        bootstrapURLKeys={{ key: THE_KEY }}
        defaultCenter={center}
        defaultZoom={zoom}
      >
        <AnyReactComponent
            lat={center.lat}
            lng={center.lng}
            text="My Marker"
            />
      </GoogleMapReact>
    </div>
  );
}
```

**Screenshots 🖥**
IMPORTANT: It always happens, in this gif it only happens the first two times, but it's because when converting video to gif the quality drops

![ezgif com-gif-maker](https://user-images.githubusercontent.com/28470320/170845913-4a7444ec-164a-4b6c-bb88-8cd96359f92a.gif)

**Environment:**
 - OS: windows
 - Browser chrome, mozilla, etc.
 - google-map-react: 2.1.10
 - react  18.1.0

**Comment by icastillejogomez** [comment]
It occurs by React 18. You probably are avoiding the library peerDependencies that recommend still using react 17

**Comment by tmilciunas** [comment]
Same thing happens in my project, with `"react": "17.0.2"` and `"google-map-react": "^2.1.10"`.

Marker has this class on it, to offset it to the center:
```
.map-pin {
  position: absolute;
  transform: translate(-50%, -100%);
  text-align: center;
}
```

Still jiggles when moving the map.

**Comment by marcosmarp** [comment]
Any news on this? I switched from `createRoot` to `ReactDOM.render` on my `index` so React would still behave as v17 but I would really like to switch back.

**Comment by Mateusz-Podemski-Forte-Digital** [comment]
I have the same problem.
It happens when I move a map using mouse or when I change `center` prop.

**Comment by SorcRR** [comment]
Same issue, please let me know when a solution for this is available. Thanks.

**Comment by guspatagonico** [comment]
First: Congrats for @istarkov and all the contributors for this great component.

> I have the same problem. It happens when I move a map using mouse or when I change `center` prop.

I'm facing the same issue and I tried several workarounds.

I've finished showing a "distractive" div overlay with a color and a message inside the map's container that shows up when the **dragend mouse event is triggered** (just before the markers flicker and lasts for 300ms).

https://user-images.githubusercontent.com/328899/178581574-fd490acd-d957-4b61-9394-1d954209f897.mp4

But... this is just a workaround, not a real solution.
Just in case someone is interested, I control overlay's visibility with "state - reducer" variables (I'm using useReducer, dispatcher, etc.) like this:

`const handleApiLoaded = (map, maps) => {
    mapRef.current = map;

    const mapOptions = {
      disableDefaultUI: true,
      fullscreenControl: true,
      mapTypeControl: true,
      mapTypeControlOptions: {
        style: maps.MapTypeControlStyle.DROPDOWN_MENU,
        mapTypeIds: ["roadmap", "terrain", "satellite", "hybrid"],
      },
    };

    map.setOptions(mapOptions);

    map.addListener("dragstart", () => {
      // console.log("GoogleMapReact -> onDragStart");
      mapStateDispatch({
        type: "UPDATE",
        fieldName: "markersOpacity",
        payload: 0.6,
      });
    });

    map.addListener("dragend", () => {
      mapStateDispatch({
        type: "UPDATE",
        fieldName: "markersVisibility",
        payload: false,
      });
      mapStateDispatch({
        type: "UPDATE",
        fieldName: "waitState",
        payload: true,
      });
      mapStateDispatch({
        type: "UPDATE",
        fieldName: "markersOpacity",
        payload: 1,
      });
      console.log("GoogleMapReact -> onDragEnd");

      setTimeout(() => {
        console.log("onDragEnd after a while...");
        mapStateDispatch({
          type: "UPDATE",
          fieldName: "markersVisibility",
          payload: true,
        });
        mapStateDispatch({
          type: "UPDATE",
          fieldName: "waitState",
          payload: false,
        });
      }, 300);
    });
  };`

I hope this could be fixed because I really want to keep on using the **google-map-react** component. I think this is a really great component, besides this issue. 

Thank you.

**Comment by marcosmarp** [comment]
@guspatagonico the workaround i'm using is switching to react 17 for the moment.. sucks but it's what it's

pd: primera vez que me encuentro un argentino por aca... saludos desde caseros jajajaja

**Comment by guspatagonico** [comment]
> @guspatagonico the workaround i'm using is switching to react 17 for the moment.. sucks but it's what it's

Hi Marcos! I considered that option but I'm trying to stick to an updated set of tools... and I'm such a stubborn ;-)
 
> pd: primera vez que me encuentro un argentino por aca... saludos desde caseros jajajaja

Nice to meet you, che! ;-) I hope we could find a fix sooner or later. Best of luck!

**Comment by asdutoit** [comment]
Did anyone manage to find a solution to this?

**Comment by rvenky125** [comment]
Is there any solution or workaround?

**Comment by SorcRR** [comment]
Guy, load the app with **ReactDOM.render** and it wont flicker anymore

**Comment by Mateusz-Podemski-Forte-Digital** [comment]
Is that possible with Next.js 12.2?

**Comment by rvenky125** [comment]
> Guys, load the app with **ReactDOM.render** and it wont flicker anymore

Can you place a code snippet here. I can't understand how can I pass state variables into it?

**Comment by icastillejogomez** [comment]
Guys, @SorcRR proposal could be a workaround but definitely is not a valid long-term solution. Use this function it's essentially use the old React17 (and older) system. 

For Next.js you have to downgrade to a Next.js version that use React 17. Definitely, not a valid solution. 

This module need to be refactored in order to be compatible with React18 and concurrent renders.

**Comment by fedemoreira93** [comment]
@marcosmarp @guspatagonico bueno ahora somos 3 argentinos!

Did you guys find a solution (not a workaround)? I was using this library in older projects (react 16) and didn't have this problem but I don't want to downgrade my react app version...

**Comment by Suzan-Dev** [comment]
Why is it actually happening in react v18? Can anybody explain me in short please.

**Comment by icastillejogomez** [comment]
> Why is it actually happening in react v18? Can anybody explain me in short please.

@Suzan-Dev the changes in react 18 render produce a flickering on the map

**Comment by guspatagonico** [comment]
> 
Hi / Hola Fede! Nice to meet you, che!

Unfortunately I did not find a definitive solution. I like this library very much, and this is the only issue I've found at least for my use case.

I hope someone could help solving this issue soon. I'd like to keep on using this library / component.

Have a nice day!

**Comment by guspatagonico** [comment]
> @marcosmarp @guspatagonico bueno ahora somos 3 argentinos!

Hey @fedemoreira93 ! Nice to meet you, compatriot 😜

> Did you guys find a solution (not a workaround)? I was using this library in older projects (react 16) and didn't have this problem but I don't want to downgrade my react app version...

Unfortunately I did not find a definitive solution.
I'd like to continue using this component / library because so far this is the only issue I've found (at least for my current use case).

Have a nice day!

**Comment by chyde** [comment]
**Confirmed** how to get the render-flicker using react `v18.x`!  @SorcRR was right to use the old method of rendering

> Can you place a code snippet here?
```jsx
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";

ReactDOM.render(
  <App />,
  document.getElementById("root")
);
````

**Comment by marcosmarp** [comment]
> **Confirmed** how to get rid of the render-flicker using react `v18.x`!  @SorcRR was right to use the old method of rendering
> 
> > Can you place a code snippet here?
> ```jsx
> import React from "react";
> import ReactDOM from "react-dom";
> import "./index.css";
> import App from "./App";
> 
> ReactDOM.render(
>   <App />,
>   document.getElementById("root")
> );
> ````
> 

@chyde This isn't a solution for React 18. Rendering with `ReactDOM.render` causes React to downgrade to v17 while using it, so you basically still in v17 while you're using this method in your entry point

**Comment by sutthikiat1** [comment]
waiting for fix

**Comment by rvenky125** [comment]
> > **Confirmed** how to get rid of the render-flicker using react `v18.x`!  @SorcRR was right to use the old method of rendering
> > > Can you place a code snippet here?
> > 
> > 
> > ```js
> > import React from "react";
> > import ReactDOM from "react-dom";
> > import "./index.css";
> > import App from "./App";
> > 
> > ReactDOM.render(
> >   <App />,
> >   document.getElementById("root")
> > );
> > ```
> 
> @chyde This isn't a solution for React 18. Rendering with `ReactDOM.render` causes React to downgrade to v17 while using it, so you basically still in v17 while you're using this method in your entry point
> 
> Check at your console while using this rendering method in React 18 and you'll see a warning about React downgrading to v17

This was solved. But we need a reliable fix.

**Comment by astorozhevsky** [comment]
We are facing the same issue, and now we are temporarily using a workaround, but we need a reliable fix so that we can use the new method of rendering (React v18.x).

**Comment by kkallasm** [comment]
Any updates on this?

**Comment by barroudjo** [comment]
Same problem here. I'd be interested in seeing the workaround you use (other than ReactDOM.render...).

**Comment by samueldusek** [comment]
I am facing the same issue. 😞 Does anybody has any progress on this? 🙂

**Comment by nathnhughes** [comment]
Yep, also experiencing the same issue with React/React Dom 18.2...

Would love to know if there's a workaround that doesn't involve downgrading

**Comment by kaspar-naaber** [comment]
Any updates on this?

**Comment by barroudjo** [comment]
I hate to say it, but seeing no contributors answer this issue, and having a fairly simple use case, I removed google-map-react and used google-map directly. I learned some interesting things in the process. The big takeaway is that it seems google-map-react is allowing us to do things that are not kosher with respect to the google-map api (such as allowing any html markup for the markers, which clearly google-map vanilla does not allow).
So my guess is that this library was able to work around the limitations of google-map, but the new way React18 renders does not allow this to work well anymore... And fixing it is either impossible, or very complicated.

Could contributors let us know if this is more or less the case ? @istarkov @timhwang21 @karldanninger @itsmichaeldiego

**Comment by fedemoreira93** [comment]
@kaspar-naaber Now there's an official react wrapper for google maps. I'm gonna use it the next time. R.I.P this lib.

**Comment by Vanmeeganathan** [comment]
I am also facing the same issue. I started facing this as soon as I upgraded to React 18. Please help with a solution which does not require downgrading React.

**Comment by AdoGaspar** [comment]
I tried many different approaches to solve the issue, unfortunately only think which helped for now was ReactDOM.render :/

**Comment by wescopeland** [comment]
We fixed this by forking google-map-react and applying some patches. You will get an annoying `flushSync` error all over the place, but markers will no longer jump all over the place.

In _src/google_map.js_:

```js
// These setTimeout calls were wrapped with ReactDOM.flushSync().

ReactDOM.flushSync(() => {
  setTimeout(
    () => {
      // to detect size
      this._setViewSize();
      if (
        this._isCenterDefined(this.props.center || this.props.defaultCenter)
      ) {
        this._initMap();
      }
    },
    0,
    this
  );
});

...

ReactDOM.flushSync(() => {
  setTimeout(() => this._initMap(), 0);
});
```

In _src/google_map_markers.js_:

```js
ReactDOM.flushSync(() => {
  this.setState(
    state,
    () =>
      (state.children || []).length !== prevChildCount &&
      this._onMouseChangeHandler()
  );
});
```

In _src/marker_dispatcher.js_:

```js
getChildren() {
  if (
    this.gmapInstance &&
    this.gmapInstance.props &&
    this.gmapInstance.props.children
  ) {
    return this.gmapInstance.props.children;
  }

  return undefined;
}
```

In _src/google_map.js_:

```js
if (this.markersDispatcher_) {
  this.markersDispatcher_.emit('kON_CHANGE');
}

...

if (
  !shallowEqual(this.props.hoverDistance, prevProps.hoverDistance) &&
  this.markersDispatcher_
) {
  this.markersDispatcher_.emit('kON_MOUSE_POSITION_CHANGE');
}

...

if (this_.markersDispatcher_) {
  this_.markersDispatcher_.emit('kON_MOUSE_POSITION_CHANGE');
}

...

if (this.markersDispatcher_) {
  this.markersDispatcher_.emit('kON_CLICK', event);
}
```

Alternatively you can npm install `google-map-react-concurrent` from npm. **Be sure to pin the version to 2.2.1. The latest, 2.2.2 will have issues.** No maintenance or support is guaranteed from this forked package.

```
npm install --save google-map-react-concurrent@2.2.1
```

**Comment by vlafranca** [comment]
Any update on this please ?

**Comment by fedemoreira93** [comment]
@vlafranca check my last comment, is not longer necessary to use a 3rd party library.

**Comment by wescopeland** [comment]
This issue occurs in the official wrapper as well: https://github.com/googlemaps/react-wrapper/issues/642

**Comment by AlpeshSorathiya** [comment]
I am still facing with latest commit. is there any timeline?

**Comment by imayankbisht** [comment]
In my case, I was using coordinates as a prop for my map component after removing the props it works for me with no flickering

hope it might help for you

**Comment by dungld96** [comment]
Any update on this please ?

**Comment by MicheleFatticcioni** [comment]
Any update about this issue? It's really annoying

**Comment by elisabeth0bangoura** [comment]
it persists in "react": "^18.2.0"  too

**Comment by btwxyz** [comment]
up!

**Comment by ZFW777** [comment]
Still occurring in
"@react-google-maps/api": "^2.20.3",
"react": "^18.3.1",

**Comment by dungld96** [comment]
> Any update on this please ?
3 years!

**Comment by Hartha-disty** [comment]
Still waiting for a real fix
