### ISSUE TITLE
Point on map "jumping" when zoom in/out

### ISSUE THREAD

**Issue by abraztsov** [google-map-react/google-map-react#556]
Hi team, lib version is 0.31.0. When I zoomIn/Out dots/marks/points on my map jumping (change their location for a second then stands to new one)

```
<GoogleMap
 className={styles.Map}
 options={(maps) => ({
  streetViewControl: false,
  panControl: false,
  zoomControl: false,
  mapTypeControl: false,
  scrollwheel: false,
  streetViewControlOptions: {
   position: maps.ControlPosition.TOP_RIGHT
  }
 })}
 bootstrapURLKeys={{
  key: MAP_API_KEY,
  language: 'en',
  region: 'en'
 }}
 center={{ lat: latitude, lng: longitude }}
 onGoogleApiLoaded={this.props.onGoogleApiLoaded}
 defaultZoom={17}
>
 <MapPoint lat={latitude} lng={longitude} />
</GoogleMap>

const MapPoint = (props) => {
 const { className, onClick } = props;
 return <span className={cn(styles.MapPoint, className)} onClick={onClick} />;
};
```

**Comment by jasondecastro** [comment]
Would love a solution to this.

**Comment by cybot1711** [comment]
Me 2

**Comment by pbwuxus** [comment]
+1

**Comment by Shachar16290** [comment]
I updated the package to the latest version and it is working now

**Comment by pbwuxus** [comment]
i use 0.34(lasest) and i get this problem still

**Comment by sladiri** [comment]
In our project an update from 0.24.0 to the current version 0.34.0 did seem to help.

**Comment by itsmichaeldiego** [comment]
@sladiri @pbwuxus @cybot1711 @jasondecastro @abraztsov Guys, I just updated to latest version and it works great. Version: `0.34.0`

**Comment by fabrii** [comment]
@itsmichaeldiego hi!, we are working with 0.34.0 and still have the issue

**Comment by itsmichaeldiego** [comment]
@fabrii Can you provide your code? I can provide this working example: https://github.com/itsmichaeldiego/google-map-react-examples

**Comment by itsmichaeldiego** [comment]
@fabrii @sladiri @pbwuxus @cybot1711 @jasondecastro @abraztsov

Follow the next steps:

- Make sure that version is >= 0.34.0:
```
  "dependencies": {
    "google-map-react": "^0.34.0",
```

- Make sure version is not specified in bootstrapURLKeys:

```
<GoogleMapReact
    bootstrapURLKeys={{
      key: process.env.REACT_APP_MAP_KEY,
      // v: '3.31',
    }}
/>
```

- Run: 
  - `rm -rf node_modules/`
  - `yarn cache clean` or `npm cache clean`
  - `yarn` or `npm install`

- Try again

**Comment by abraztsov** [comment]
v 0.34.0 - fixed my problem

**Comment by nickpolet** [comment]
v1.0.0 fixes this issue perfectly.

**Comment by itsmichaeldiego** [comment]
@sladiri @pbwuxus @cybot1711 @jasondecastro @abraztsov

v1.0.0 fixes the issue.

Thanks @nickpolet for confirming!
