### ISSUE TITLE
Error: ENOTDIR: not a directory, lstat node_modules/google-map-react/.github/ISSUE_TEMPLATE/BUG_REPORT.md

### ISSUE THREAD

**Issue by hinok** [google-map-react/google-map-react#834]
**Describe the bug 🐛**

After upgrading `google-map-react` `1.1.4   ❯  1.1.6`, I got error
```
Error: ENOTDIR: not a directory, lstat '/Users/<myacc>/Desktop/Dev/my-project/node_modules/google-map-react/.github/ISSUE_TEMPLATE/BUG_REPORT.md'
```

**To Reproduce 🔍**

1. Install package using yarn

```
yarn add google-map-react
```

**Expected behavior 💭**

No error after installing

**Screenshots 🖥**

![Zrzut ekranu 2020-02-19 o 18 06 23](https://user-images.githubusercontent.com/1313605/74856565-991d4280-5342-11ea-8ecf-ed63b52d540e.png)

**Environment:**

 - OS: macOS
 - yarn 1.22.0
 - google-map-react 1.1.4   ❯  1.1.6

**Additional context**

I cannot reproduce this error in a fresh directory (new project).

**Comment by creaumond** [comment]
https://github.com/google-map-react/google-map-react/issues/830

**Comment by masull** [comment]
We have the same issue. It is blocking the rest of our yarn upgrades now.

**Comment by BasakKamil** [comment]
I have this same problem while I try update my app...
:(
yarn 1.22.0
google-map-react 1.1.6 
![Zrzut ekranu 2020-02-26 o 21 37 16](https://user-images.githubusercontent.com/47579294/75385720-8e355580-58e0-11ea-9eba-cd49682cff07.png)

**Comment by flymans** [comment]
Resolved this issue by manually deleting node_modules/google-map-react/.github/ISSUE_TEMPLATE file. Hope this helps.

**Comment by BasakKamil** [comment]
App working on Mac but when I commit changes then Netlify show this...
![Zrzut ekranu 2020-02-27 o 23 13 02](https://user-images.githubusercontent.com/47579294/75491894-f48ca780-59b6-11ea-9564-d00081c1a369.png)

**Comment by matheusnasser** [comment]
Same here, when trying to upload to a Linux machine in the Amazon s3

**Comment by BasakKamil** [comment]
For me, It was a solution:
npm install --save @babel/runtime

pon., 9 mar 2020 o 13:11 Matheus Nasser <notifications@github.com>
napisał(a):

**Comment by hinok** [comment]
@BasakKamil It doesn't solve the issue.

As I wrote here https://github.com/google-map-react/google-map-react/issues/830#issuecomment-588417686

@giuliogallerini created a PR https://github.com/google-map-react/google-map-react/pull/835

We have to wait for merge of that PR and publishing new version.

**Comment by itsmichaeldiego** [comment]
This was merged and released, check https://github.com/google-map-react/google-map-react/pull/835#issuecomment-600289215
